### ISSUE TITLE
How to properly write INCLUDEPATH of BOOST in trojan-qt.pro

### ISSUE THREAD

**Issue by UzminTid** [trojan-gfw/trojan-qt#3]
As I working o the windows version of this project,I find a writing style problem of adding BOOST lib.

For now  I use this code in trojan-qt.pro in my branch (only BOOST-related are shown)
```
win32{
    INCLUDEPATH += $$(BOOST_PATH)/include/
    LIBS += -L$$(BOOST_PATH)/lib
}
//BOOST_PATH is the root path of boost.For me,it is "C:\Boost"
```
However,the tree of BOOST_PATH  folder is a little inconvenience.
```
Boost
├─include
│  └─boost-1_69
│      └─boost
│          ├─accumulators
│                 accumulators.hpp
│                .........
└─lib
      libboost_atomic-mgw73-mt-d-x32-1_69.a
        .........
```
The ``LIBS += -L$$(BOOST_PATH)/lib`` will work ,that's good.

But the includepath is wrong because it is related to boost's version and I believe writing something like `INCLUDEPATH += $$(BOOST_PATH)/include/boost-1_69` or other magic-path will make those other working on this project very uncomfortable.
And I also dont think moving those hpp file  is a good idea.

That what the problem is, how should I properly write the  INCLUDEPATH of BOOST in trojan-qt.pro.

_As a beginner of both Qt and open source community I consist all your guidance are my pleasure.And sorry again for my awful English.._

**Comment by GreaterFire** [comment]
Thank you for your intent to contribute to the `trojan-qt` project! This project is maintained by @lightbob. He has made a lot of updates on the master branch but hasn't pushed them yet. You may want to wait until he pushes his changes to start contributing. By the look of things, you'll have to set `INCLUDEPATH` to `$$(BOOST_PATH)/include/boost-1_69`. It doesn't look like that there is a portable solution to this.
